// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function EndRound() {
  return window['go']['main']['GameData']['EndRound']();
}

export function StartStopGame() {
  return window['go']['main']['GameData']['StartStopGame']();
}
